services:
  nginx:
    build: ./nginx/
    image: pindurapp-nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  app:
    build: .
    image: pindurapp-slim:1.0.0
    volumes:
     - ./pindurapp:/app/pindurapp
    ports:
      - 5000:5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
    entrypoint: gunicorn -w 2 pindurapp:app --bind 0.0.0.0
  postgres:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data 
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}



