services:
  app:
    image: pindurapp
  postgres:
    image: postgres
    volumes:
      - ./db/:/var/lib/postgresql/data 
    environment: 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pindurapp


